package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "message",
    hdrs = [
        "device_messages.h",
        "header.h",
        "light_messages.h",
        "message.h",
    ],
    deps = [],
)
